### ISSUE TITLE
Fix all versions in the conda environment

### ISSUE THREAD

**Issue by jan-janssen** [din14970/example_reproducible_workflow#1]
Currently the conda environment only specifies the hyperspy version but I guess it is recommended to fix the versions of all dependencies that you import in the Jupyter notebook:

- hyperspy
- numpy
- Matplotlib
- skimage

**Comment by din14970** [comment]
Ah you are right, I will fix that! But in the docker image I created the correct versions should be correctly "frozen" in right? Anyway the main issue with reproducibility here in my opinion is the fact that the "large" dataset is hosted elsewhere, so if I remove that file it breaks. LFS would work but the data limit and bandwith for that on github is quite low.

**Comment by jan-janssen** [comment]
I agree the data storage is the biggest issue, one way would be to use the MPCDF resources: 
https://www.mpcdf.mpg.de/services/data/gitlab
They even have their own binder which requires the repository to be located on the MPCDF gitlab: 
https://binderdemo.mpcdf.mpg.de
But it is important to remember that also docker hub is fighting the huge data load, so I am not sure how long the images are going to be available: They first announced: "First, a new inactive image retention policy was introduced that will automatically delete images hosted in free accounts that have not been used in 6 months." but then delayed this change after complains from the developer base: 
https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/
https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/

**Comment by din14970** [comment]
Yes I had heard of these issues with docker hub - this image is just a demo and contains almost nothing, yet with the ubuntu image (alpine is apparently a bit of a problem with conda), miniconda, etc it's 3.5 Gb. But in principle one could host the docker image as archive somewhere else.

**Comment by jan-janssen** [comment]
I guess the size is not so much the problem, when the underlying stack is actively used as docker hub only stores the delta for a given image. In case of pyiron our images are based on the jupyter-notebook images which already have conda setup https://github.com/pyiron/docker-stacks/blob/master/base/Dockerfile

**Comment by jan-janssen** [comment]
Finally in case Apple is right and everybody is switching to ARM chips in the next five years, then it is anyway hard to maintain compatibility, as every docker container is architecture specific, so the X86 Docker containers are not compatible to the current ARM architecture.

**Comment by din14970** [comment]
True, this is a pain for my rasberry pi that has docker, but no images to run on it.

**Comment by jan-janssen** [comment]
The jupyter notebook images are available on https://github.com/step21/raspi-jupyter-docker-stacks and conda-forge is working on migrating the required packages https://conda-forge.org/status/#aarch64andppc64leaddition
